# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# title: Your awesome title
# email: your-email@domain.com
# description: > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

contributions_to_date: $20,203

current_focus:
  title: Environment
  # Note: have to cap off the body with "…" manually:
  body: "The stats on climate change are staggering. To name just a few: 2016 was the hottest year on record—as was 2015, and as was 2014 before that. We’ve entered a “mass extinction” period, wherein we’re losing species at record rates. An estimated 13 million Americans are at risk of being displaced by 2100 as a result of rising sea levels. And experts have deemed climate change “the biggest gl…"
  url: https://blog.vocalminority.us/announcing-our-march-focus-the-environment-59fb22a16025

# Uncomment this if you want to show the "To Be Announced" placeholder:
# current_org:
#   image: "<div style='font-size: 7rem; color: #ccc;'>…</div>"
#   title: To Be Announced
#   body: "Our selection committee is currently researching a number of NPOs in this space. We look for organizations where our impact can be significant. Read more about out <a href='/about.html#criteria'>selection process</a>."

# Uncomment this if you want to show an actual organization:
current_org:
  image: <img src="/images/npo-logos/crmw@2x.png" alt="Coal River Mountain Watch" width="195"/>
  title: Coal River Mountain Watch
  location: Naoma, WV
  # Note: have to cap off the body with "…" manually:
  body: "The mission of Coal River Mountain Watch is to stop the destruction of our communities and environment by mountaintop removal mining, to improve the quality of life i…"
  url: https://blog.vocalminority.us/vocal-minority-funds-coal-river-mountain-watchs-fight-for-environmental-justice-41cdb74b5f6d

grantees:
  - month: February
    year: 2017
    name: "Thrive: A Refugee Support Program"
    short_name: Thrive # On home page
    description: Founded in 2011, Thrive is a team of volunteers dedicated to assisting refugees post-resettlement in Grand Rapids, Michigan. They bridge the gap between the 3–6 months of assistance a government resettlement program can provide and the reality of what it takes to get settled. Thrive connects each family with volunteers who can help and mentor them as they adjust to a new place and culture, local agencies and services that will help them succeed, and a warm community to make them feel at home in their new country.
    video: https://blog.vocalminority.us/a-thank-you-message-from-thrive-f342375be95a
    website: https://refugeesupportgr.com/
    amount: $5,345
    focus: Refugee Support
    contributors: 87
    slug: thrive
  - month: January
    year: 2017
    name: Making Contact Radio
    short_name: Making Contact Radio # On home page
    description: Founded in 1994, Making Contact is an independent non-profit organization committed to investigative journalism, in-depth critical analysis, the promotion of civic participation and the dissemination of educational material. What began as a 13-week experiment in highlighting progressive community perspectives has become an enduring platform for underrepresented groups and community voices.
    video: '???'
    website: http://www.radioproject.org/
    amount: $4,896
    focus: Independent Media
    contributors: 93
    slug: making-contact
  - month: December
    year: 2016
    name: Not In Our Town
    short_name: Not In Our Town # On home page
    description: Founded in 1995, Not In Our Town (NIOT) began in Billings, Montana, when a community of working people stood up to a series of hate crimes by white supremacists. After attacks on a Native American woman’s house, an African-American church, and a Jewish family’s home, the entire town refused to be silent and fearful. They stood up to hate with petitions, marches, community outreach, but most importantly — with peace and unity. It worked.
    video: https://blog.vocalminority.us/a-thank-you-from-our-december-grantee-not-in-our-town-86d6dc0f5905
    website: http://www.radioproject.org/
    amount: $4,651
    focus: Combatting Hate
    contributors: 65
    slug: not-in-our-town

top_nav:
  - title: 'About'
    url: '/about.html'
  - title: 'Blog'
    url: 'https://blog.vocalminority.us'
  - title: 'Grantees'
    url: '/grantees.html'
  - title: 'FAQ'
    url: '/faq.html'

# Build settings
markdown: kramdown
gems:
  - octopress-autoprefixer
exclude:
  - Gemfile
  - Gemfile.lock

# Sass settings
