# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# title: Your awesome title
# email: your-email@domain.com
# description: > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

contributions_to_date: $67,421

current_focus:
  title: Dreamers
  # Note: have to cap off the body with "…" manually:
  body: "In less than a month, roughly 700,000 DACA recipients face deportation if Congress doesn’t reach a deal to extend their protected status. We sincerely hope that Congress will reach a deal on an issue that has overwhelming bipartisan support, but we shouldn’t take any chances. Our members will fund an organization working to support DREAMers during this incredibly trying time."
  url:

# Uncomment this if you want to show the "To Be Announced" placeholder:
current_org:
  image: "<div style='font-size: 7rem; color: #ccc;'>…</div>"
  title: To Be Announced
  body: "Our selection committee is currently researching a number of NPOs in this space. We look for organizations where our impact can be significant. Read more about out <a href='/about.html#criteria'>selection process</a>."

# Uncomment this if you want to show an actual organization:
# current_org:
#   image: <img src="/images/npo-logos/centro-presente.png" alt="Centro Presente" width="140"/>
#   title: Centro Presente
#   location: Boston, MA
#   # Note: have to cap off the body with "…" manually:
#   body: "Centro Presente is a member-driven, state-wide Latin American immigrant organization dedicated to the self-determination and self-sufficiency of the Latin American immigrant community of Massachusetts."
#   url: http://www.cpresente.org

grantees:
  - month: January
    year: 2017
    name: "Centro Presente"
    short_name: Centro Presente # On home page
    description: Centro Presente is a member-driven, state-wide Latin American immigrant organization dedicated to the self-determination and self-sufficiency of the Latin American immigrant community of Massachusetts.
    video:
    website: http://www.cpresente.org
    amount: TBA
    focus: El Salvador
    contributors: TBA
    slug: centro-presente
  - month: December
    year: 2017
    name: "Mission Asset Fund"
    short_name: MAF # On home page
    description: Founded in 2007, Mission Asset Fund is a nonprofit organization on a mission to create a fair financial marketplace for hardworking families.
    video: https://vimeo.com/250689570
    website: https://missionassetfund.org/
    amount: $5,215
    focus: Income Inequality
    contributors: 80
    slug: mission-asset-fund
  - month: November
    year: 2017
    name: "The Educational Fund to Stop Gun Violence"
    short_name:  EFSGV # On home page
    description: Founded in 1978, The Educational Fund to Stop Gun Violence develops and implements evidence-based policy advocacy campaigns that reduce gun death and injury.
    video: https://www.youtube.com/watch?v=MI9FT5oZ5fY
    website: http://efsgv.org/
    amount: $5,069
    focus: Gun Violence
    contributors: 81
    slug: efsgv
  - month: October
    year: 2017
    name: "Foundation for Puerto Rico"
    short_name: FPR # On home page
    description: With an intelligent eye on the future, the foundation for Puerto Rico is forward-thinking and dedicated to driving smart infrastructure change to Puerto Rico.
    video: https://www.youtube.com/watch?v=y2ajmDXQw1A
    website: https://www.foundationforpuertorico.org/
    amount: $4,919
    focus: Puerto Rico Recovery
    contributors: 80
    slug: puert-rico-recovery
  - month: September
    year: 2017
    name: "Cajun Relief"
    short_name: Cajun Relief # On home page
    description: The Cajun Relief Foundation helps citizens meet needs and connect volunteers with those impacted by hurricanes, earthquakes and disasters of all kinds.
    video: https://www.youtube.com/watch?v=wdaclBG2P2I
    website: http://cajunrelief.org/
    amount: $5,395
    focus: Rebuilding Texas
    contributors: 80
    slug: cajun-relief
  - month: August
    year: 2017
    name: "HEALS, Inc."
    short_name: HEALS, Inc. # On home page
    description: It is HEALS' mission to deliver accessible, quality, school-based, primary health care for children through collaborative efforts with the school system and the medical, dental and mental communities.
    video: https://www.facebook.com/wearethevocalminority/videos/808244922670960
    website: https://healsinc.org
    amount: $5,296
    focus: Healthcare
    contributors: 84
    slug: heals
  - month: July
    year: 2017
    name: "VoteRiders"
    short_name: VoteRiders # On home page
    description: VoteRiders' mission is to ensure that all citizens are able to exercise their right to vote. They achieve this by informing and helping citizens secure their voter ID through education and assistance.
    video: https://blog.vocalminority.us/a-thank-you-message-from-voteriders-a97863da202d
    website: https://voteriders.org
    amount: $5,315
    focus: Voting Rights
    contributors:
    slug: vote-riders
  - month: June
    year: 2017
    name: "Alliance for Climate Education"
    short_name: ACE # On home page
    description: Alliance for Climate Education’s mission is to educate young people on the science of climate change and empower them to take action.
    video:
    website: https://acespace.org/
    amount: $5,264
    focus: Environmental Justice
    contributors: 87
    slug: ace
  - month: May
    year: 2017
    name: "Las Americas Immigrant Advocacy Center"
    short_name: Las Americas # On home page
    description: Las Americas is a 29-year-old, homegrown, non-profit dedicated to serving the legal needs of low income immigrants, including refugees, victims of crime, and families seeking reunification.
    video: https://www.facebook.com/wearethevocalminority/videos/772909849537801/
    website: http://las-americas.org/
    amount: $5,322
    focus: Immigration
    contributors: 88
    slug: las-americas
  - month: April
    year: 2017
    name: "VoteRunLead"
    short_name: VoteRunLead # On home page
    description: VoteRunLead is a national nonpartisan organization that unleashes the power of women leaders in democracy through training, technology and community.
    video: https://www.facebook.com/wearethevocalminority/videos/759338874228232/
    website: https://voterunlead.org/
    amount: $5,423
    focus: Community Service
    contributors: 90
    slug: vote-run-lead
  - month: March
    year: 2017
    name: "Coal River Mountain Watch"
    short_name: CRMW # On home page
    description: The mission of Coal River Mountain Watch is to stop the destruction of our communities and environment by mountaintop removal mining, to improve the quality of life in our area and to help rebuild sustainable communities.
    video: https://blog.vocalminority.us/a-thank-you-message-from-coal-river-mountain-watch-ed41a41bc9f7
    website: http://crmw.net/
    amount: $5,311
    focus: Environmental Justice
    contributors: 90
    slug: coal-river
  - month: February
    year: 2017
    name: "Thrive: A Refugee Support Program"
    short_name: Thrive # On home page
    description: Founded in 2011, Thrive is a team of volunteers dedicated to assisting refugees post-resettlement in Grand Rapids, Michigan. They bridge the gap between the 3–6 months of assistance a government resettlement program can provide and the reality of what it takes to get settled. Thrive connects each family with volunteers who can help and mentor them as they adjust to a new place and culture, local agencies and services that will help them succeed, and a warm community to make them feel at home in their new country.
    video: https://blog.vocalminority.us/a-thank-you-message-from-thrive-f342375be95a
    website: https://refugeesupportgr.com/
    amount: $5,345
    focus: Refugee Support
    contributors: 87
    slug: thrive
  - month: January
    year: 2017
    name: Making Contact Radio
    short_name: Making Contact Radio # On home page
    description: Founded in 1994, Making Contact is an independent non-profit organization committed to investigative journalism, in-depth critical analysis, the promotion of civic participation and the dissemination of educational material. What began as a 13-week experiment in highlighting progressive community perspectives has become an enduring platform for underrepresented groups and community voices.
    video: https://www.facebook.com/wearethevocalminority/videos/692257594269694/
    website: http://www.radioproject.org/
    amount: $4,896
    focus: Independent Media
    contributors: 93
    slug: making-contact
  - month: December
    year: 2016
    name: Not In Our Town
    short_name: Not In Our Town # On home page
    description: Founded in 1995, Not In Our Town (NIOT) began in Billings, Montana, when a community of working people stood up to a series of hate crimes by white supremacists. After attacks on a Native American woman’s house, an African-American church, and a Jewish family’s home, the entire town refused to be silent and fearful. They stood up to hate with petitions, marches, community outreach, but most importantly — with peace and unity. It worked.
    video: https://blog.vocalminority.us/a-thank-you-from-our-december-grantee-not-in-our-town-86d6dc0f5905
    website: http://www.radioproject.org/
    amount: $4,651
    focus: Combating Hate
    contributors: 65
    slug: not-in-our-town

top_nav:
  - title: 'About'
    url: '/about.html'
  - title: 'Blog'
    url: 'https://blog.vocalminority.us'
  - title: 'Grantees'
    url: '/grantees.html'
  - title: 'FAQ'
    url: '/faq.html'

# Build settings
markdown: kramdown
gems:
  - octopress-autoprefixer
exclude:
  - Gemfile
  - Gemfile.lock

# Sass settings
